### ISSUE TITLE
Running the Stella emulator with a rom as parameter

### ISSUE THREAD

**Issue by feitgemel** [stella-emu/stella-emu.github.io#6]
Hi,

Is it possible to run the Stella emulator with a specific rom as a parameter ? or
Is it possible to define anywhere a starting rom with one of Stella config app screen ?

Thanks
Eran

**Comment by sa666666** [comment]
The correct place to create issues for Stella is with the app itself; this is the Github space for the Stella webpage itself.

In any event, yes, Stella accepts commandline arguments for all its functionality, including specifying the ROM.  More info can be found at https://stella-emu.github.io/docs/index.html#CommandLine.
